name: pydriller
language: python
language_version: "3.6"
analysis_runtime: "Python >=3.10"
target_files: ["Git history for datascience/"]
trigger:
  command: "python tool-triggers/pydriller/run_pydriller.py ."
