name: cosmic-ray
language: python
language_version: "2.7"
analysis_runtime: "Python >=3.10"
target_files: ["datascience/model.py", "tests/test_pipeline.py"]
trigger:
  command: "cosmic-ray init tool-triggers/cosmic-ray/cosmic-ray.toml cosmic.sqlite && cosmic-ray exec tool-triggers/cosmic-ray/cosmic-ray.toml cosmic.sqlite"
